springdoc:
  swagger-ui:
    path: /api/docs.html
    tags-sorter: alpha
    operations-sorter: method
spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/data
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  jpa:
    hibernate:
      ddl-auto: update
konfero:
  security:
    allowed-origins:
      - http://localhost:8080/
      - http://localhost:3000/
    redirect-uri: http://localhost:8080/api/docs.html