spring:
  application:
    name: konfero_backend
  jpa:
    defer-datasource-initialization: true
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mail:
    username: the.immortalcoders@gmail.com
    password: vzysvlirbdvcwkti
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-message: always
konfero:
  security:
    login-uri: /api/oauth2/authorize
    logout-uri: /api/oauth2/logout