spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/data
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://kni.prz.edu.pl:47473/login/oauth2/code/google
            client-id: 613981732432-ru776ugru9amm581881k2pef05ugjv5q.apps.googleusercontent.com
            client-secret: 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
  jpa:
    hibernate:
      ddl-auto: update
konfero:
  security:
    allowed-origins:
      - http://kni.prz.edu.pl:47474
      - http://kni.prz.edu.pl:47473
    redirect-uri: http://kni.prz.edu.pl:47474
    logout-redirect-uri: http://kni.prz.edu.pl:47474