spring:
  application:
    name: konfero_backend
  jpa:
    defer-datasource-initialization: true
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 613981732432-ru776ugru9amm581881k2pef05ugjv5q.apps.googleusercontent.com
            client-secret: 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
server:
  error:
    include-message: always
konfero:
  security:
    login-uri: /api/oauth2/authorize
    logout-uri: /api/oauth2/logout