spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: ${BACKEND_DOMAIN}/login/oauth2/code/google
            client-id: 613981732432-ru776ugru9amm581881k2pef05ugjv5q.apps.googleusercontent.com
            client-secret: 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
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      cookie:
        domain: ${COOKIE_DOMAIN}
konfero:
  security:
    allowed-origins: ${ALLOWED_ORIGINS}
    redirect-uri: ${FRONTEND_DOMAIN}
    logout-redirect-uri: ${FRONTEND_DOMAIN}
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false